### ISSUE TITLE
Missing definition for enframe function + NSL toolbox missing from Duangudom Model

### ISSUE THREAD

**Issue by k4vi** [CUC-Acoustics/Auditory-Saliency-Models#1]
Hi! Line 21 in /Kaya Model/waveform.m uses `enframe(out, fram, fram)`, but it seems this function is not defined in any other file. There are a few different implementations available online (written by different people), but which implementation is being referenced in this case? [This one](https://github.com/YouriT/matlab-speech/blob/master/MATLAB_CODE_SOURCE/voicebox/enframe.m) is compatible with the rest of the code, but is it the intended implementation?

Additionally, /Duangudom Model/Duangudom_Saliency.m says that the "NLS toolbox" is provided in the same folder, but I think this should be the "NSL toolbox"? This toolbox is also missing from the folder.

**Comment by xiongxiansong** [comment]
Sorry, that should be NSL toolbox, The download link of NSL toolbox is as follows: http://nsl.isr.umd.edu/downloads.html

And the enframe function is in the voice toolbox, The download link is as follows: http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html

**Comment by xiongxiansong** [comment]
> Hi! Line 21 in /Kaya Model/waveform.m uses `enframe(out, fram, fram)`, but it seems this function is not defined in any other file. There are a few different implementations available online (written by different people), but which implementation is being referenced in this case? [This one](https://github.com/YouriT/matlab-speech/blob/master/MATLAB_CODE_SOURCE/voicebox/enframe.m) is compatible with the rest of the code, but is it the intended implementation?
> 
> Additionally, /Duangudom Model/Duangudom_Saliency.m says that the "NLS toolbox" is provided in the same folder, but I think this should be the "NSL toolbox"? This toolbox is also missing from the folder.


Sorry, that should be NSL toolbox, The download link of NSL toolbox is as follows: http://nsl.isr.umd.edu/downloads.html

And the enframe function is in the voice toolbox, The download link is as follows: http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html
